### ISSUE TITLE
Got an error while trying to build Nox Soc

### ISSUE THREAD

**Issue by arunvthampi** [aignacio/nox#1]
Hello, I encountered an error while attempting to get the Nox Soc on Arty 7. I attempted to remove version 2.3 of FuseSoC and installed version 1.8 instead. However, I'm now encountering an issue with missing files in FuseSoC. Could you please confirm the version of FuseSoC were you using?

![Screenshot from 2024-03-27 07-04-08](https://github.com/aignacio/nox/assets/112419174/8416bad3-3940-4d34-8fad-959ac4fd7392)

**Comment by aignacio** [comment]
Hey @arunvthampi,
can you try to build the bootloader ROM first?

```bash
make -C sw/bootloader all
fusesoc library add core  .
fusesoc run --run --target=a7_synth core:nox:v0.0.1
```

I'll update the readme instructions to consider that. Btw, I just tested with the latest FuseSoC 2.3 and it worked, here is the command log below: (the wbuart error is expected)

```bash
❯ fusesoc library add core  .
INFO: Interpreting sync-uri '.' as location for local provider.
❯ fusesoc run --run --target=a7_synth core:nox:v0.0.1
ERROR: Core file /home/aignacio/projects/nox/xlnx/rtl/wbuart32/wbuart32.core is in CAPI1 format, which is not supported any more since FuseSoC 2.0. The core file is ignored. Please migrate your cores to the CAPI2 file format, or use FuseSoC
1.x as stop-gap.
INFO: Preparing core:nox:v0.0.1:0
INFO: Setting up project
INFO: Running
vivado -notrace -mode batch -source core_nox_v0.0.1_0.tcl


****** Vivado v2022.2 (64-bit)
  **** SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
  **** IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
    ** Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.

source core_nox_v0.0.1_0.tcl -notrace
create_project: Time (s): cpu = 00:00:05 ; elapsed = 00:00:06 . Memory (MB): peak = 1246.488 ; gain = 3.023 ; free physical = 303 ; free virtual = 18769
WARNING: [Runs 36-537] File /home/aignacio/projects/nox/build/core_nox_v0.0.1_0/a7_synth-vivado/vivado_hook_synth_design_pre.tcl is not part of fileset utils_1, but has specified as a Tcl hook script for run(s) synth_1. This file will not be
 handled as part of the project for archive and other project based functionality.
WARNING: [Runs 36-537] File /home/aignacio/projects/nox/build/core_nox_v0.0.1_0/a7_synth-vivado/vivado_hook_opt_design_post.tcl is not part of fileset utils_1, but has specified as a Tcl hook script for run(s) impl_1. This file will not be h
andled as part of the project for archive and other project based functionality.
...
```

**Comment by arunvthampi** [comment]
Hi @aignacio ,

I tried to implement as per you had given me the instructions.

## Steps to that I followed

> git clone https://github.com/aignacio/nox.git
>git submodule init

In this command I got an error "Cloning into '/home/user/Project/nox/bus_arch_sv_pkg'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:aignacio/bus_arch_sv_pkg.git' into submodule path '/home/user/Project/nox/bus_arch_sv_pkg' failed
Failed to clone 'bus_arch_sv_pkg' a second time, aborting". So I cloned it directly from the github.
>cd nox/
>git clone https://github.com/aignacio/bus_arch_sv_pkg.git
>git submodule update
>make -C sw/bootloader all
>fusesoc library add core  .
>fusesoc run --run --target=a7_synth core:nox:v0.0.1

##Observed Behaviour
After providing the command, I am getting this which I have attached with this comment
![Screenshot from 2024-03-28 06-48-00](https://github.com/aignacio/nox/assets/112419174/6a1db6c5-e96b-48f0-a2e0-f2f81fdc72bb)

##Doubts
Should I first connect with Arty a7-100t using Jtag and then try on these commands

**Comment by aignacio** [comment]
Hey @arunvthampi,

I have updated the master branch to avoid having the bus arch issues in terms of permissions, could you try in a fresh new folder/terminal the following:
```bash
git clone --recursive https://github.com/aignacio/nox.git
cd nox
make -C sw/bootloader all
fusesoc library add core  .
fusesoc run --run --target=a7_synth core:nox:v0.0.1
```
I have tried this setup in a new docker container and it has been executing fine without any issues. Just for heads up, at the end of the FuseSoC run, it'll try to program the board, so make sure the following is correct:

1. Your FPGA arty 7 board is connected to the USB
2. Your user has permission to program the board through the USB, check this [link](https://digilent.com/reference/programmable-logic/arty-a7/arty_a7_100_risc_v/start#troubleshooting)

**Comment by arunvthampi** [comment]
Hi @aignacio,

Actually I am new to docker. Is there anything that I need to do in the commands for using docker container.

Also I have tried the commands on a new terminal. After running the command:
>fusesoc run --run --target=a7_synth core:nox:v0.0.1

its still showing this
![Screenshot from 2024-03-28 18-45-18](https://github.com/aignacio/nox/assets/112419174/2d3f24f8-995f-4ffa-b005-936f4ff717a4)
Just the heads up, I haven't connected with arty 7. Shouldn't I get something like this even before connecting to arty a7
![Screenshot from 2024-03-28 18-51-10](https://github.com/aignacio/nox/assets/112419174/f1e483d9-86f3-4de9-af32-05fd68cded3f)

Should I receive a mcs file and manually provide it to vivado? 

My aim is to benchmark nox core using coremarks, also get area and power utilisation in vivado and cadence genus tool

**Comment by aignacio** [comment]
Hey @arunvthampi,

the vivado project creation will happen before you connect the board, as soon as you run fusesoc command. I'm not exact sure why fusesoc is not building the project on your end. Can you try the same setup in a different machine? Also, maybe get some help from fusesoc repo.
